# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0c10e4e5540ae66fac492f04d013d87010afad85fa5a27ef7e3f41bfc80751151a16b790053ad3b67e58aaba3fb8ecd96a65230df0181d3bfa4cc03a2a0c9d15

test:
  secret_key_base: 92041821c77b728a55e625cde10905efd61c70b0529a89fe2394ed62284d685eae4d63f2523a294394f9ee79d02fe78c34254e7e3a4ca88dd8f094618cf00eb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
